/**
 * Experiment 22: Auto-learn definition for Gene class
 */
ks.type = "OWL File"
ks.fileName = "../../../ontology/AMD_final_clean.owl"
reasoner.type = "closed world reasoner"
reasoner.sources = { ks }
lp.type = "posNegStandard"

// All Gene instances
lp.positiveExamples = {
    "http://example.org/amd#CFH",
    "http://example.org/amd#C3",
    "http://example.org/amd#C2",
    "http://example.org/amd#CFB",
    "http://example.org/amd#ARMS2",
    "http://example.org/amd#HTRA1",
    "http://example.org/amd#ApoE",
    "http://example.org/amd#CX3CR1",
    "http://example.org/amd#BF",
    "http://example.org/amd#LOC387715",
    "http://example.org/amd#CFI",
    "http://example.org/amd#PLEKHA1",
    "http://example.org/amd#VEGFR"
}

// Everything else
lp.negativeExamples = {
    "http://example.org/amd#Ranibizumab",
    "http://example.org/amd#Verteporfin",
    "http://example.org/amd#Aspirin",
    "http://example.org/amd#OCT",
    "http://example.org/amd#Drusen",
    "http://example.org/amd#VEGF",
    "http://example.org/amd#Smoking",
    "http://example.org/amd#Lutein",
    "http://example.org/amd#Glaucoma",
    "http://example.org/amd#AMD",
    "http://example.org/amd#Ultrasound",
    "http://example.org/amd#Lipofuscin",
    "http://example.org/amd#Endophthalmitis"
}

la.type = "celoe"
la.maxExecutionTimeInSeconds = 60
la.noisePercentage = 15.0
