/**
 * Experiment 19: Same as 14 (dual mechanism) but ELTL
 */
ks.type = "OWL File"
ks.fileName = "../../ontology/AMD_final_clean.owl"
reasoner.type = "closed world reasoner"
reasoner.sources = { ks }
lp.type = "posNegStandard"

lp.positiveExamples = {
    "http://example.org/amd#Ranibizumab",
    "http://example.org/amd#Bevacizumab",
    "http://example.org/amd#Aflibercept",
    "http://example.org/amd#Conbercept",
    "http://example.org/amd#Avastin"
}

lp.negativeExamples = {
    "http://example.org/amd#Verteporfin",
    "http://example.org/amd#OT-551",
    "http://example.org/amd#Saffron",
    "http://example.org/amd#Aspirin",
    "http://example.org/amd#Sirolimus",
    "http://example.org/amd#Copaxone",
    "http://example.org/amd#Photocoagulation",
    "http://example.org/amd#Vitrectomy",
    "http://example.org/amd#Rheopheresis",
    "http://example.org/amd#Acetazolamide"
}

la.type = "org.dllearner.algorithms.el.ELLearningAlgorithm"
la.maxExecutionTimeInSeconds = 60
la.noisePercentage = 15.0
