ks.type = "OWL File"
ks.fileName = "../../../ontology/AMD_final_clean.owl"
reasoner.type = "closed world reasoner"
reasoner.sources = { ks }
acc.type = "pred_acc"
acc.balanced = true
lp.type = "posNegStandard"
lp.accuracyMethod = acc
lp.positiveExamples = {
    "http://example.org/amd#Ranibizumab",
    "http://example.org/amd#Bevacizumab",
    "http://example.org/amd#Aflibercept"
}
lp.negativeExamples = {
    "http://example.org/amd#Aspirin",
    "http://example.org/amd#Vitrectomy"
}
la.type = "celoe"
la.maxExecutionTimeInSeconds = 30
la.noisePercentage = 0
