ks.type = "OWL File"
ks.fileName = "../../../ontology/AMD_final_clean.owl"
reasoner.type = "closed world reasoner"
reasoner.sources = { ks }
acc.type = "jaccard"
lp.type = "posNegStandard"
lp.accuracyMethod = acc
lp.positiveExamples = {
    "http://example.org/amd#Drusen",
    "http://example.org/amd#Lutein",
    "http://example.org/amd#Zeaxanthin",
    "http://example.org/amd#Lipofuscin"
}
lp.negativeExamples = {
    "http://example.org/amd#VEGF",
    "http://example.org/amd#S1P",
    "http://example.org/amd#rs11200638",
    "http://example.org/amd#rs1061170"
}
la.type = "celoe"
la.maxExecutionTimeInSeconds = 30
la.noisePercentage = 0
