/**
 * Experiment 13: WetAMD drugs using ELTL algorithm
 */
ks.type = "OWL File"
ks.fileName = "../AMD3.owl"
reasoner.type = "closed world reasoner"
reasoner.sources = { ks }
lp.type = "posNegStandard"

lp.positiveExamples = {
    "http://example.org/amd#Ranibizumab",
    "http://example.org/amd#Aflibercept",
    "http://example.org/amd#Bevacizumab",
    "http://example.org/amd#Verteporfin",
    "http://example.org/amd#Lucentis",
    "http://example.org/amd#Eylea",
    "http://example.org/amd#Conbercept",
    "http://example.org/amd#Avastin",
    "http://example.org/amd#SRT"
}

lp.negativeExamples = {
    "http://example.org/amd#Saffron",
    "http://example.org/amd#Rheopheresis",
    "http://example.org/amd#Copaxone",
    "http://example.org/amd#OT-551",
    "http://example.org/amd#Sirolimus",
    "http://example.org/amd#Aspirin",
    "http://example.org/amd#Zinc",
    "http://example.org/amd#Copper",
    "http://example.org/amd#Acetazolamide",
    "http://example.org/amd#Phenylephrine"
}

la.type = "org.dllearner.algorithms.el.ELLearningAlgorithm"
la.maxExecutionTimeInSeconds = 60
la.noisePercentage = 15.0
